# Generated by Django 5.2.3 on 2025-07-05 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostelItem',
            fields=[
                ('hostelid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('totalflr', models.IntegerField()),
                ('totalrooms', models.IntegerField()),
                ('totalstaff', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelid', models.IntegerField(blank=True, null=True)),
                ('floornum', models.IntegerField()),
                ('roomnum', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('currentoccupy', models.IntegerField()),
                ('roomtype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentItem',
            fields=[
                ('stdid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('contactnum', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('parentname', models.CharField(max_length=100)),
                ('parentnum', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('admissiondate', models.DateField(blank=True, null=True)),
                ('floornum', models.IntegerField(blank=True, null=True)),
                ('roomnum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HostelFeeItem',
            fields=[
                ('feeid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentdate', models.DateField()),
                ('duedate', models.DateField()),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_managmt_app.studentitem')),
            ],
        ),
    ]
