# Generated by Django 5.2.3 on 2025-07-22 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HostelItem",
            fields=[
                ("hostelid", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("totalflr", models.IntegerField()),
                ("totalrooms", models.IntegerField()),
                ("totalstaff", models.IntegerField()),
                (
                    "hostelcontact",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "floornum",
                    models.IntegerField(
                        choices=[
                            (1, "Floor-1"),
                            (2, "Floor-2"),
                            (3, "Floor-3"),
                            (4, "Floor-4"),
                            (5, "Floor-5"),
                            (6, "Floor-6"),
                            (7, "Floor-7"),
                            (8, "Floor-8"),
                            (9, "Floor-9"),
                            (10, "Floor-10"),
                        ]
                    ),
                ),
                (
                    "roomtype",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("double", "Double"),
                            ("triple", "Triple"),
                            ("ac", "AC"),
                            ("non-ac", "Non-AC"),
                        ],
                        max_length=20,
                    ),
                ),
                ("roomnum", models.PositiveIntegerField(unique=True)),
                ("capacity", models.PositiveIntegerField()),
                ("currentoccupy", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="StaffItem",
            fields=[
                ("staffid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=50)),
                ("contactnum", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("salary", models.IntegerField()),
                ("joindate", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="StudentItem",
            fields=[
                ("stdid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=50)),
                ("dob", models.DateField(blank=True, null=True)),
                ("contactnum", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=50)),
                ("parentname", models.CharField(max_length=100)),
                ("parentnum", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=100)),
                ("admissiondate", models.DateField(blank=True, null=True)),
                ("floornum", models.IntegerField(blank=True, null=True)),
                ("roomnum", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="StaffLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hostel_managmt_app.staffitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutPassItem",
            fields=[
                ("outpassid", models.AutoField(primary_key=True, serialize=False)),
                ("reason", models.CharField(max_length=50)),
                ("whereto", models.CharField(max_length=50)),
                ("outat", models.DateTimeField()),
                ("innat", models.DateTimeField()),
                ("status", models.BooleanField(default=False)),
                (
                    "approvedby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hostel_managmt_app.staffitem",
                    ),
                ),
                (
                    "std",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hostel_managmt_app.studentitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HostelFeeItem",
            fields=[
                ("feeid", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paymentdate", models.DateField()),
                ("duedate", models.DateField()),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "std",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hostel_managmt_app.studentitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hostel_managmt_app.studentitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisitorItem",
            fields=[
                ("visitorid", models.AutoField(primary_key=True, serialize=False)),
                ("visitorname", models.CharField(max_length=100)),
                ("relation", models.CharField(max_length=50)),
                ("visitdate", models.DateTimeField()),
                (
                    "std",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hostel_managmt_app.studentitem",
                    ),
                ),
            ],
        ),
    ]
