# Generated by Django 5.2.3 on 2025-07-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel_managmt_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hostelfeeitem",
            old_name="std",
            new_name="std_id",
        ),
        migrations.AlterField(
            model_name="staffitem",
            name="contactnum",
            field=models.BigIntegerField(),
        ),
    ]
