# Generated by Django 5.2.3 on 2025-07-10 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_managmt_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffItem',
            fields=[
                ('staffid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('contactnum', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.IntegerField()),
                ('joindate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='hostelid',
        ),
        migrations.AddField(
            model_name='hostelitem',
            name='hostelcontact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='currentoccupy',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='floornum',
            field=models.IntegerField(choices=[(1, 'Floor-1'), (2, 'Floor-2'), (3, 'Floor-3'), (4, 'Floor-4'), (5, 'Floor-5'), (6, 'Floor-6'), (7, 'Floor-7'), (8, 'Floor-8'), (9, 'Floor-9'), (10, 'Floor-10')]),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomnum',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomtype',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('ac', 'AC'), ('non-ac', 'Non-AC')], max_length=20),
        ),
        migrations.CreateModel(
            name='OutPassItem',
            fields=[
                ('outpassid', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=50)),
                ('whereto', models.CharField(max_length=50)),
                ('outat', models.DateTimeField()),
                ('innat', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_managmt_app.studentitem')),
                ('approvedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel_managmt_app.staffitem')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorItem',
            fields=[
                ('visitorid', models.AutoField(primary_key=True, serialize=False)),
                ('visitorname', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=50)),
                ('visitdate', models.DateTimeField()),
                ('std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_managmt_app.studentitem')),
            ],
        ),
    ]
