# Generated by Django 5.2.3 on 2025-07-11 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_managmt_app', '0002_staffitem_stafflog_studentlog_remove_room_hostelid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafflog',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_managmt_app.staffitem'),
        ),
        migrations.AlterField(
            model_name='studentlog',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_managmt_app.studentitem'),
        ),
    ]
