# Generated by Django 5.2.3 on 2025-07-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hostel_managmt_app", "0002_rename_std_hostelfeeitem_std_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hostelfeeitem",
            old_name="std_id",
            new_name="std",
        ),
    ]
